global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
   - rules.yml
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

  - job_name: jenkins
    scrape_interval: 10s
    metrics_path: /prometheus
    static_configs:
      - targets: ['localhost:8080']  # Replace with your Jenkins instance IP and                                                                                         port

  - job_name: docker
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9323']  # Replace with your Docker instance IP and                                                                                         port

